### ISSUE TITLE
Question: How can oclif be integrated with a web terminal?

### ISSUE THREAD

**Issue by kpayson** [oclif/oclif#461]
I have an existing oclif app.  I would like to add a teminal window to an angular web application possibly using the xterm.js library.  Can OCLIF be integrated into a web based terminal?  Please share any examples or suggestions that you have.

**Comment by RasPhilCo** [comment]
Would be interested to see if anyone has done this yet, I have not.

**Comment by amphro** [comment]
I've done this before using heroku with [ttyd](https://github.com/tsl0922/ttyd). The repo is private, but here are the key bits. We also checked in the ttyd executable which is how the `# Set up executables` works in the docker image.

**heroku.yml**
```yml
build:
  docker:
    web: Dockerfile
run:
  web: /app/bin/ttyd --ping-interval 15 -p $PORT -c $USERNAME:$PASSWORD -t fontSize=15 bash
```

**Dockerfile**
```
# Use full-fat Debian with nodejs preinstalled 
# for a more realistic CLI environment
FROM node:buster

# Set up any app files you need
COPY ./package.json /app/package.json
COPY ./build /app/build
RUN /app/build

# Set up executables
COPY ./bin /app/bin
RUN chmod +x /app/bin/ttyd

# Set PATH to include cli binary and set starting directory (only works locally)
RUN echo "export PATH=$PATH:/app/node_modules/.bin; cd /app/dreamhouse" >> /etc/bash.bashrc

# Set PATH to include cli binary and set starting directory (only works on Heroku)
RUN echo "export PATH=$PATH:/app/node_modules/.bin; cd /app/dreamhouse" >> /.bashrc

# Set user as non-root (for local parity with Heroku)
RUN useradd -m localtest
USER localtest

# No CMD; Heroku doesn't use it, and local entrypoint is set via docker-compose.yml
```

**docker-compose.yml**
```
version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    entrypoint: /app/bin/ttyd --ping-interval 15 -p $PORT -c $USERNAME:$PASSWORD -t fontSize=15 bash
```

build
```
#!/bin/bash

cd /app

npm install <your oclif cli>@<version>
```

Good luck!
