### ISSUE TITLE
Is it possible to integrate oclif-dev packaging with github actions?

### ISSUE THREAD

**Issue by LakshmiRavali** [oclif/oclif#642]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
 Can we automate `oclif-dev pack ` process using github actions?

**Comment by LakshmiRavali** [comment]
Thanks, but I have added directly in github actions itself. Something like this:
```
jobs:
   oclifRelease:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: artifact_name_ubuntu
            asset_name: asset_name.deb
            command_name: sudo oclif-dev pack:deb
          - os: macos-latest
            artifact_name: artifact_name.exe
            asset_name: asset_name.exe
            command_name: oclif-dev pack:win
          - os: macos-latest
            artifact_name: artifact_name.pkg
            asset_name: asset_name.pkg
            command_name: oclif-dev pack:macos

    steps:
      - run: npm cache clear & npm ci
      - run: npm install -g @oclif/dev-cli
      - run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install makensis
          fi
      - run: ${{ matrix.command_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
```
